name: CrateReloaded
main: com.hazebyte.crate.cratereloaded.CorePlugin
version: ${project.version}
author: dinosaur
website: crate.hazebyte.com
depend:
softdepend: [Essentials, Vault, HolographicDisplays, Holograms, Citizens, Multiverse-Core, PlaceholderAPI, CMI, DecentHolograms]
api-version: 1.13