name: Feature Request
description: Suggest a new feature or enhancement for CrateReloaded
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when... / It would be helpful if..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: "Add a new animation type that displays rewards in a circular pattern..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: "Instead of a new animation, we could modify the existing ROULETTE animation to support..."

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how this feature would be used on your server or in your plugin.
      placeholder: |
        We run a survival server with 200+ players and want to create seasonal crates with unique animations.
        This feature would allow us to...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: |
        Screenshots, mockups, or links to similar features in other plugins would be helpful!

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my server
        - High - Critical for my server
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - I can implement this feature myself and submit a PR
        - I can help test this feature
        - I'm interested in contributing but need guidance
        - I cannot contribute to implementation
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions to ensure this is not a duplicate
          required: true
        - label: This feature request is within the scope of CrateReloaded (crate/reward system)
          required: true
